### PR TITLE
Hibernate gotchas page

### PR DESCRIPTION
**Pull request by nguyenfilip**

### CODE REVIEW

**Comment by nguyenfilip** [comment]
@awood Is there a line numbering feature in Kramdown? Couldn't find one in the docs. In case not, I will add the specific numbers manually before merging this

**Comment by awood** [comment]
Do you mean adding line numbers to the code samples?  That can be done, but I don't remember how off the top of my head.  If that's what you want, I can look into it.

**Comment by awood** [comment]
Feel free to self merge.  It looks good to me.

**Comment by nguyenfilip** [comment]
@awood Looks great, I added the numbering to all snippets gonna merge this. Thanks!

**Pull request merged**
